services:
  api:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/game?schema=public
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - api_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: game

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  api_node_modules: